services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  auth-service:
    build: ./auth-service
    depends_on:
      rabbitmq:
        condition: service_started
    environment:
      - RABBIT_HOST=rabbitmq
    volumes:
      - ./auth-service:/app
    command: ['./start.sh']
    ports:
      - "8001:8000"

  course-service:
    build: ./course-service
    depends_on:
      rabbitmq:
        condition: service_started
    environment:
      - RABBIT_HOST=rabbitmq
    volumes:
      - ./course-service:/app
    command: ['./start.sh']
    ports:
      - "8002:8000"

  notification-service:
    build: ./notification-service
    depends_on:
      rabbitmq:
        condition: service_started
    environment:
      - RABBIT_HOST=rabbitmq
    volumes:
      - ./notification-service:/app
    command: ['./start.sh']
    ports:
      - "8003:8000"
